#!/bin/sh

cd $(dirname $0)
docker run --rm -it -p 8000:8000 -v $(pwd):/docs -u "$(id -u):$(id -g)" squidfunk/mkdocs-material:4.6.3

# docker run --rm -it -v $(pwd):/docs squidfunk/mkdocs-material build
# docker run --rm -it -v $(pwd):/docs squidfunk/mkdocs-material gh-deploy
