#!/bin/sh

# docker pull squidfunk/mkdocs-material

cd $(dirname $0)
docker run --rm -it -p 8000:8000 -v $(pwd):/docs squidfunk/mkdocs-material

# docker run --rm -it -v $(pwd):/docs squidfunk/mkdocs-material build
# docker run --rm -it -v $(pwd):/docs squidfunk/mkdocs-material gh-deploy
