#! /bin/bash
notedown --match=fenced ResultAnalysisUsingPython.md -o tmp.ipynb
jupyter nbconvert --execute --to html --template basic tmp.ipynb

cat >index.md <<END
previous_page_disabled: true
next_page_disabled: true

END
cat tmp.html >> index.md
rm tmp.*

